cf:
  butlers:
#     pcfone: cf-butler-chipper-hyrax.apps.pcfone.io
    pcfone: gateway-0c616a55-df28-47ad-8b13-be3531f451fb.apps.pcfone.io/cf-butler
    #ironleg: cf-butler.apps.demo.ironleg.me
  sslValidationSkipped: true

management:
  endpoints:
    web:
      exposure:
        include: info,health,metrics,scheduledtasks,loggers,prometheus
  endpoint:
    health:
      show-details: always
    metrics:
      enabled: true
    prometheus:
      enabled: true
spring:
  profiles: cloud

  cloud:
    config:
      enabled: true
